name: Ruby Cloudbeam
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # - name: Setup test database
      #   env:
      #     RAILS_ENV: test
      #     PGHOST: localhost
      #     PGUSER: myapp
      #   run: |
      #     bin/rails db:setup

      - name: Run tests
        run: bundle exec rake test

      - name: Formatting and Security Checks
        run: |
          bundle exec rubocop
          bundle exec brakeman -z
          gem install bundle-audit
          bundle-audit update
          bundle-audit
